### ISSUE TITLE
这是一个需求开发的issue

### ISSUE THREAD

**Issue by hnuyx** [hnuyx/TestRepo#2]
这是一个需求的issue

**Comment by hnuyx** [comment]
@maohuaming 申请开发 size: 1.0 Deadline: 2018-08-29

**Comment by hnuyx** [comment]
申请开发 deadline 2018-08-29 size:1 [@maohuaming]

**Comment by maohuaming** [comment]
@hnuyx 括号要去掉。

**Comment by hnuyx** [comment]
申请开发 deadline 2018-08-29 size:1 @maohuaming

**Comment by maohuaming** [comment]
@hnuyx 请创建分支，提交文件并创建PR。切记按照ICP流程图中说明来做，如果出错，会记违规一次。

**Comment by hnuyx** [comment]
merged files
